ServiWeb/ServiWeb/Models/Bodega.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodega
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bodega()
        {
            this.BodegaProducto = new HashSet<BodegaProducto>();
        }
    
        public int idBodega { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodegaProducto> BodegaProducto { get; set; }
    }
}

ServiWeb/ServiWeb/Models/ViewModels/BodegaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ServiWeb.Models.ViewModels
{
    public class BodegaViewModel
    {
        [Required]
        [StringLength(400)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    }
}

ServiWeb/ServiWeb/Controllers/BodegaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiWeb.Models;
using ServiWeb.Models.ViewModels;

namespace ServiWeb.Controllers
{
    public class BodegaController : Controller
    {
        // GET: Bodega
        public ActionResult Index()
        {
            List<ListaBodegaViewModel> lst;
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                lst = (from d in db.Bodega
                       select new ListaBodegaViewModel
                       {
                           IdBodega = d.idBodega,
                           Nombre = d.nombre,
                           Descripcion = d.descripcion
                       }).ToList();
            }
            return View(lst);
        }
        public ActionResult Nuevo()
        {
            return View();
        }
        // POST: Bodega
        [HttpPost]
        public ActionResult Nuevo(BodegaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBORDENEntities1 db = new DBORDENEntities1())
                    {
                        var oBodega = new Bodega();
                        oBodega.nombre = model.Nombre.ToString().ToUpper();
                        oBodega.descripcion = model.Descripcion;
                        db.Bodega.Add(oBodega);
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int Id)
        {
            ListaBodegaViewModel model = new ListaBodegaViewModel();
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                var oBodega = db.Bodega.Find(Id);
                model.Nombre = oBodega.nombre;
                model.Descripcion = oBodega.descripcion;
                model.IdBodega = oBodega.idBodega;
            }
            return View(model);
        }

        // POST: Bodega
        [HttpPost]
        public ActionResult Editar(ListaBodegaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (DBORDENEntities1 db = new DBORDENEntities1())
                    {
                        var oBodega = db.Bodega.Find(model.IdBodega);
                        oBodega.nombre = model.Nombre.ToString().ToUpper();
                        oBodega.descripcion = model.Descripcion;
                        db.Entry(oBodega).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Eliminar(int Id)
        {
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                var oBodega = db.Bodega.Find(Id);
                db.Bodega.Remove(oBodega);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ServiWeb/ServiWeb/Views/Bodega/Editar.cshtml
@model ServiWeb.Models.ViewModels.ListaBodegaViewModel
@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm("Editar", "Bodega", FormMethod.Post))
{
<div class="row">
    <h2>@ViewBag.Title</h2>
    @Html.HiddenFor(model => model.IdBodega)
    <div class="container">
        <div class="row">
            <div class="col-6">
                Nombre Bodega<br />
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 400 } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
            <div class="col-6">
                Descripción <br />
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
    <br />
    <div class="col-md-1">
        <input type="submit" value="Guardar" class="btn btn-default bg-warning" />
    </div>
    </div>
</div>
}

ServiWeb/ServiWeb/Views/Bodega/Index.cshtml
@model List<ServiWeb.Models.ViewModels.ListaBodegaViewModel>
@{
    ViewBag.Title = "Bodega";
}

<h2>@ViewBag.Title</h2>

<div class="container-fluid" style="width:100%">
    @Html.ActionLink("Nuevo", "Nuevo", null, new { @class = "btn btn-default bg-warning" })

</div>
<br />
<table table id="example" class="table table-striped table-bordered"
       style="width:100%">
    <thead>
        <tr>
            <th style="width: 5%">
                Id
            </th>
            <th style="width: 35%">
                Nombre
            </th>
            <th style="width: 40%">
                Descripción
            </th>
            <th style="width: 20%">
                Acción
            </th>
</thead>
    <tbody>

        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdBodega)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                <a class="btn btn-default bg-warning" href="~/Bodega/Editar/@item.IdBodega">Editar</a>
                @Html.ActionLink("Eliminar", "Eliminar", new { id = item.IdBodega }, new { onclick = "return confirm('Esta seguro que desea eliminar el registro?');", @class = "btn btn-default bg-warning" })
            </td>
        </tr>
        }
    </tbody>
</table>

ServiWeb/ServiWeb/Views/Bodega/Nuevo.cshtml
@model ServiWeb.Models.ViewModels.BodegaViewModel
@{
    ViewBag.Title = "Crear Bodega";
}


@using (Html.BeginForm("Nuevo", "Bodega", FormMethod.Post))
{
<div class="row">
    <h2>@ViewBag.Title</h2>
    <div class="container">
        <div class="row">
            <div class="col-6">
                Nombre Bodega<br />
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", maxlength = 400 } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
            <div class="col-6">
                Descripción<br />
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control", maxlength = 400 } })
            </div>
        </div>
        <br />
        <div class="col-6">
            <input type="submit" value="Guardar" class="btn btn-default bg-warning" />
        </div>
    </div>
</div>
        }