ServiWeb/ServiWeb/Models/Cliente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Orden = new HashSet<Orden>();
        }
    
        public int idCliente { get; set; }
        public string nitcc { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public string correo { get; set; }
        public string contacto { get; set; }
        public string correoContacto { get; set; }
        public string telContacto { get; set; }
        public string ciudad { get; set; }
        public int idAsesor { get; set; }
    
        public virtual Asesor Asesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden> Orden { get; set; }
    }
}

ServiWeb/ServiWeb/Models/ViewModels/ClienteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiWeb.Models.ViewModels
{
    public class ClienteViewModel
    {
        [Required(ErrorMessage = "Nit es requerido")]
        [StringLength(20)]
        public string Nitcc { get; set; }

        [Required(ErrorMessage = "Nombre es requerido")]
        [StringLength(200)]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Dirección es requerido")]
        [StringLength(200)]
        public string Direccion { get; set; }

        [Required(ErrorMessage = "Telefono es requerido")]
        [StringLength(50)]
        public string Telefono1 { get; set; }

        public string Telefono2 { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string Correo { get; set; }

        public string Contacto { get; set; }

        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string CorreoContacto { get; set; }

        public string TelContacto { get; set; }

        [Required(ErrorMessage = "Ciudad es requerido")]
        [StringLength(200)]
        public string Ciudad { get; set; }

        public int IdCiudad { get; set; }

        public string NombreCiudad { get; set; }

        [Required(ErrorMessage = "Asesor es requerido")]
        public int IdAsesor { get; set; }

        public virtual Asesor Asesor { get; set; }
    }
}

ServiWeb/ServiWeb/Controllers/ClienteController.cs
using ServiWeb.Models;
using ServiWeb.Models.ViewModels;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiWeb.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            List<ListaClienteViewModel> lst;
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                lst = (from d in db.Cliente
                       select new ListaClienteViewModel
                       {  
                           IdCliente = d.idCliente,
                           Nitcc = d.nitcc,
                           Nombre = d.nombre,
                           Direccion = d.direccion,
                           Telefono1 = d.telefono1,
                           Telefono2 = d.telefono2,
                           Correo = d.correo,
                           Contacto = d.contacto,
                           CorreoContacto = d.correoContacto,
                           TelContacto = d.telContacto,
                           IdAsesor = d.idAsesor,
                           Ciudad = d.ciudad                       
                       }
                       ).ToList();
            }
            return View(lst);
        }

        // GET: Cliente
        [HttpGet]
        public ActionResult Nuevo()
        {
            //Cargar Lista Asesor
            List<ClienteViewModel> lstAsesor = new List<ClienteViewModel>();
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                lstAsesor = (from d in db.Asesor.Where(d=> d.estado == true)
                       select new ClienteViewModel
                       {   IdAsesor = d.idAsesor,
                           Nombre = d.nombre
                       }).ToList();                
            }
            ViewData["IdAsesor"] = new SelectList(lstAsesor, "IdAsesor", "Nombre");

            //Cargar Lista Ciudad
            List<CiudadViewModel> ltsCiudad = new List<CiudadViewModel>();
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                ltsCiudad = (from x in db.Ciudad
                    select new CiudadViewModel
                    {
                        IdCiudad = x.idCiudad,
                        Nombre = x.nombre                     
                    }).ToList();
            }
            ViewBag.IdCiudad = new SelectList(ltsCiudad, "IdCiudad", "Nombre");
            return View();
        }

        // POST: Cliente
        [HttpPost]
        public ActionResult Nuevo(ClienteViewModel model, FormCollection form)
        {
            try
            {
                int ciudadId = model.IdCiudad;
                string ciudad;
                using (DBORDENEntities1 db1 = new DBORDENEntities1())
                {
                    ciudad = db1.Ciudad.FirstOrDefault(x => x.idCiudad == ciudadId).nombre;
                }
                using (DBORDENEntities1 db = new DBORDENEntities1())
                    {
     
                        var oCliente = new Cliente();
                        oCliente.nitcc = model.Nitcc;
                        oCliente.nombre = model.Nombre;
                        oCliente.direccion = model.Direccion;
                        oCliente.telefono1 = model.Telefono1;
                        oCliente.telefono2 = model.Telefono2;
                        oCliente.correo = model.Correo;
                        oCliente.contacto = model.Contacto;
                        oCliente.correoContacto = model.CorreoContacto;
                        oCliente.telContacto = model.TelContacto;
                        oCliente.idAsesor = model.IdAsesor;
                        oCliente.ciudad = ciudad;
                        db.Cliente.Add(oCliente);
                        db.SaveChanges();                        
                }
                return RedirectToAction("Index");

            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Editar(int Id)
        {
            List<CiudadViewModel> ltsCiudad = new List<CiudadViewModel>();
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                ltsCiudad = (from x in db.Ciudad
                             select new CiudadViewModel
                             {
                                 IdCiudad = x.idCiudad,
                                 Nombre = x.nombre
                             }).ToList();
            }
            ViewBag.IdCiudad = new SelectList(ltsCiudad, "IdCiudad", "Nombre");

            List<ClienteViewModel> lstAsesor = new List<ClienteViewModel>();
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                lstAsesor = (from d in db.Asesor.Where(d => d.estado == true)
                             select new ClienteViewModel
                             {
                                 IdAsesor = d.idAsesor,
                                 Nombre = d.nombre
                             }).ToList();
            }
            ViewData["IdAsesor"] = new SelectList(lstAsesor, "IdAsesor", "Nombre");

            ListaClienteViewModel model = new ListaClienteViewModel();
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                var oCliente = db.Cliente.Find(Id);
                model.Nombre = oCliente.nombre;
                model.Direccion = oCliente.direccion;
                model.Telefono1 = oCliente.telefono1;
                model.Telefono2 = oCliente.telefono2;
                model.Correo = oCliente.correo;
                model.Contacto = oCliente.contacto;
                model.CorreoContacto = oCliente.correoContacto;
                model.TelContacto = oCliente.telContacto;
                model.IdAsesor = oCliente.idAsesor;
                model.Ciudad = oCliente.ciudad;
                model.IdCliente = oCliente.idCliente;
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Editar(ListaClienteViewModel model, FormCollection form)
        {
            try
            {
                int ciudadId = model.IdCiudad;
                string ciudad;
                using (DBORDENEntities1 db1 = new DBORDENEntities1())
                {
                    ciudad = db1.Ciudad.FirstOrDefault(x => x.idCiudad == ciudadId).nombre;
                }


                if (ModelState.IsValid)
                {
                    using (DBORDENEntities1 db = new DBORDENEntities1())
                    {
                        var oCliente = db.Cliente.Find(model.IdCliente);
                        oCliente.nombre = model.Nombre.ToString().ToUpper();
                        oCliente.direccion = model.Direccion.ToString().ToUpper();
                        oCliente.telefono1 = model.Telefono1.ToString();
                        oCliente.telefono2 = model.Telefono2;
                        oCliente.correo = model.Correo;
                        oCliente.contacto = model.Contacto;
                        oCliente.correoContacto = model.CorreoContacto;
                        oCliente.telContacto = model.TelContacto;
                        oCliente.idAsesor = model.IdAsesor;
                        oCliente.ciudad = ciudad;
                        db.Entry(oCliente).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public ActionResult Eliminar(int Id)
        {
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                var oCliente = db.Cliente.Find(Id);
                db.Cliente.Remove(oCliente);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ServiWeb/ServiWeb/Views/Cliente/Editar.cshtml
@model ServiWeb.Models.ViewModels.ListaClienteViewModel
@{
    ViewBag.Title = "Editar";
}


@using (Html.BeginForm("Editar", "Cliente", FormMethod.Post))
{
<div class="row">
    <h2>@ViewBag.Title</h2>
    @Html.HiddenFor(model => model.IdCliente)
    <div class="container">
        <div class="row">
            <div class="col-md-3 mb-3">
                <label>Nombre</label>
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 200 } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3 mb-3">
                <label>Dirección</label>
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 200 } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3 mb-3">
                <label>Telefono1</label>
                @Html.EditorFor(model => model.Telefono1, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 50 } })
                @Html.ValidationMessageFor(model => model.Telefono1, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3 mb-3">
                <label>Telefono2</label>
                @Html.EditorFor(model => model.Telefono2, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 50 } })
            </div>
            <div class="col-md-3 mb-3">
                <label>Correo Electrónico</label>
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", maxlength = 200 } })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3 mb-3">
                <label>Contacto</label>
                @Html.EditorFor(model => model.Contacto, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 100 } })
            </div>
            <div class="col-md-3 mb-3">
                <label>Correo Contacto</label>
                @Html.EditorFor(model => model.CorreoContacto, new { htmlAttributes = new { @class = "form-control", maxlength = 200 } })
            </div>
            <div class="col-md-3 mb-3">
                <label>Teléfono Contacto</label>
                @Html.EditorFor(model => model.TelContacto, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 50 } })
            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-2 mb2">
                <label>Asesor</label>
                @Html.EditorFor(model => model.IdAsesor, new { htmlAttributes = new { @class = "form-control", maxlength = 200 } })
            </div>
            <div class="col-md-2 mb2">
                <label> Ciudad </label>
                @Html.DropDownList("IdCiudad", null, "Seleccione....", new { @class = "form-control" })
                @if(!ViewData.ModelState.IsValid && ViewData.ModelState["IdCiudad"] != null && ViewData.ModelState["IdCiudad"].Errors.Count > 0)
                {
                    <span class="text-danger">@ViewData.ModelState["IdCiudad"].Errors[0].ErrorMessage</span>
                }
            </div>

        </div>
        <div class="col-md-3 mb-3">
            <br />
            <input type="submit" value="Guardar" class="btn btn-default bg-warning" />
        </div>
    </div>
</div>
}

ServiWeb/ServiWeb/Views/Cliente/Index.cshtml
@model List<ServiWeb.Models.ViewModels.ListaClienteViewModel>
@{
    ViewBag.Title = "Cliente";
}

<h2>@ViewBag.Title</h2>

<div class="container-fluid" style="width:100%">
    @Html.ActionLink("Nuevo", "Nuevo", null, new { @class = "btn btn-default bg-warning" })

</div>
<br />
    <table table id="example" class="table table-striped table-bordered"
           style="width:100%">
        <thead>
            <tr>
                <th style="width: 5%">
                    Id
                </th>
                <th style="width: 10%">
                    Nit o Cedula
                </th>
                <th style="width: 20%">
                    Nombre
                </th>
                <th style="width: 20%">
                    Dirección
                </th>
                <th style="width: 5%">
                    Telefono1
                </th>
                <th style="width: 5%">
                    Asesor
                </th>
                <th style="width: 10%">
                    Ciudad
                </th>
                <th style="width: 25%">
                    Acción
                </th>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdCliente)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nitcc)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Direccion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telefono1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdAsesor)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ciudad)
                    </td>
                    <td>
                        <a class="btn btn-default bg-warning" href="~/Cliente/Editar/@item.IdCliente">Editar</a>
                        @Html.ActionLink("Eliminar", "Index", new { id = item.IdCliente }, new { onclick = "return confirm('Esta seguro que desea eliminar el registro?');", @class = "btn btn-default bg-warning" })
                    </td>
                </tr>
            }
        </tbody>
    </table>

ServiWeb/ServiWeb/Views/Cliente/Nuevo.cshtml
@model ServiWeb.Models.ViewModels.ClienteViewModel
@{
    ViewBag.Title = "Crear Cliente";
}


@using (Html.BeginForm("Nuevo", "Cliente", FormMethod.Post))
{
<div class="row">
    <h2>@ViewBag.Title</h2>
    <div class="container">
        <div class="row">
            <div class="col-md-2 mb-3">
                <label>Nit</label>
                @Html.EditorFor(model => model.Nitcc, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 20 } })
                @Html.ValidationMessageFor(model => model.Nitcc, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3 mb-3">
                <label>Nombre</label>
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 200 } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3 mb-3">
                <label>Dirección</label>
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 200 } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3 mb-3">
                <label>Telefono1</label>
                @Html.EditorFor(model => model.Telefono1, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 50 } })
                @Html.ValidationMessageFor(model => model.Telefono1, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-3 mb-3">
                <label>Telefono2</label>
                @Html.EditorFor(model => model.Telefono2, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 50 } })
            </div>
            <div class="col-md-3 mb-3">
                <label>Correo Electrónico</label>
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", maxlength = 200 } })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3 mb-3">
                <label>Contacto</label>
                @Html.EditorFor(model => model.Contacto, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 100 } })
            </div>
            <div class="col-md-3 mb-3">
                <label>Correo Contacto</label>
                @Html.EditorFor(model => model.CorreoContacto, new { htmlAttributes = new { @class = "form-control", maxlength = 200 } })
            </div>
            <div class="col-md-3 mb-3">
                <label>Teléfono Contacto</label>
                @Html.EditorFor(model => model.TelContacto, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", maxlength = 50 } })
            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-2 mb-2">
                <label>Asesor</label>
                @Html.DropDownList("IdAsesor", null, "Seleccione....", new { @class = "form-control" })
                @if (!ViewData.ModelState.IsValid && ViewData.ModelState["IdAsesor"] != null && ViewData.ModelState["IdAsesor"].Errors.Count > 0)
                {
                    <span class="text-danger">@ViewData.ModelState["IdAsesor"].Errors[0].ErrorMessage</span>
                }
            </div>
            <div class="col-md-2 mb2">
                <label>Ciudad</label>
                @Html.DropDownList("IdCiudad", null, "Seleccione....", new { @class = "form-control" })
                @if (!ViewData.ModelState.IsValid && ViewData.ModelState["IdCiudad"] != null && ViewData.ModelState["IdCiudad"].Errors.Count > 0)
                {
                    <span class="text-danger">@ViewData.ModelState["IdCiudad"].Errors[0].ErrorMessage</span>
                }
            </div>
            <div class="col-md-3 mb-3">
                <br />
                <input type="submit" value="Guardar" class="btn btn-default bg-warning" />
            </div>
        </div>
    </div>
</div>
 }