ServiWeb/ServiWeb/Models/Producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.BodegaProducto = new HashSet<BodegaProducto>();
        }
    
        public int idProducto { get; set; }
        public string referencia { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string unidadMedida { get; set; }
        public string dimension { get; set; }
        public Nullable<decimal> precioCompra { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public int idCategoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BodegaProducto> BodegaProducto { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}

ServiWeb/ServiWeb/Models/ViewModels/ProductoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ServiWeb.Models.ViewModels
{
    public class ProductoViewModel
    {
        public int IdProducto { get; set; }
        public string Referencia { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public string UnidadMedida { get; set; }
        public string Dimension { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public int IdCategoria { get; set; }

        public virtual Bodega Bodega { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}

ServiWeb/ServiWeb/Controllers/ProductoController.cs
using ServiWeb.Models;
using ServiWeb.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServiWeb.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {

            List<ListaProductoViewModel> lstProducto = new List<ListaProductoViewModel>();
            using (DBORDENEntities1 db = new DBORDENEntities1())
            {
                lstProducto = (from d in db.Producto
                       select new ListaProductoViewModel
                       {
                            IdProducto = d.idProducto,
                            Referencia = d.referencia,
                            Descripcion = d.descripcion,
                            Marca = d.marca,
                            UnidadMedida = d.unidadMedida,
                            Dimension = d.dimension,
                            PrecioCompra = d.precioCompra,                        
                            PrecioVenta = d.precioVenta,
                            IdCategoria = d.idCategoria  
                       }
                       ).ToList();
            }
            return View(lstProducto);            
        }

       

        List<SelectListItem> lstBodegaProducto;

        public void llenarBodegaXProductos(int? id)
        {
                 
            using (var db = new DBORDENEntities1())
            {
                lstBodegaProducto = (from BodProd in db.BodegaProducto
                                     join Bodega in db.Bodega
                                     on BodProd.idBodega equals
                                     Bodega.idBodega
                                     where BodProd.idProducto == id
                               select new SelectListItem
                               {
                                   Text = Bodega.nombre,
                                   Value = Bodega.idBodega.ToString()
                               }).ToList();
                lstBodegaProducto.Insert(0, new SelectListItem { Text = "Seleccione....", Value = "" });
                ViewBag.lstBodegaProducto = lstBodegaProducto;                 
            }            
        }



        List<BodegaProductoViewModel> lstExistencias;
        public void CargarExistencia(int idProducto, int idBodega)        {
            
            using (var db = new DBORDENEntities1())
            {
                lstExistencias = (from BodProd in db.BodegaProducto                            
                                     where BodProd.idProducto == idProducto && BodProd.idBodega == idBodega
                                     select new BodegaProductoViewModel
                                     {
                                         IdBodegäProducto = BodProd.idBodegaProducto,
                                         IdBodega = BodProd.idBodega,
                                         Referencia = BodProd.referencia,
                                         Existencia = BodProd.existencia

                                     }).ToList();
                ViewBag.lstExistencias = lstExistencias;                 
            }
        }


        [HttpPost]
        public ActionResult BuscarProducto(ListaProductoViewModel model)
        {        

            return View();
        }
        
    }
}

ServiWeb/ServiWeb/Views/Producto/BuscarProducto.cshtml
@model List<ServiWeb.Models.ViewModels.ListaProductoViewModel>
@{
    ViewBag.Title = "Productos";
    List<SelectListItem> lstBodegaProducto = (List<SelectListItem>)ViewBag.lstBodegaProducto;
}

<h2>@ViewBag.Title</h2>

<div class="container-fluid" style="width:100%">

    <table table id="example" class="table table-striped table-bordered"
           style="width:100%">
        <thead>
            <tr>
                <th style="width: 5%">
                    Id
                </th>
                <th style="width: 20%">
                    Referencia
                </th>
                <th style="width: 40%">
                    Descripción
                </th>
                <th style="width: 15%">
                    Marca
                </th>
                <th style="width: 10%">
                    Dimensión
                </th>
                <th style="width: 5%">
                    IdCategoria
                </th>
                <th style="width: 5%">
                    Acción
                </th>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Referencia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dimension)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdCategoria)
                    </td>
                    <td>
                        <!-- Button trigger modal -->
                        <input type="button" value="Agregar" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal@(item.IdProducto)" onclick="cargarCombo(@item.IdProducto)">
                        <div class="modal fade" id="exampleModal@(item.IdProducto)" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Producto</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-md-6 mb-2">
                                                @Html.DisplayFor(modelitem => item.IdProducto)
                                                @Html.TextBox("IdProducto", null, new { @class = "form-control", @ReadOnly = true })
                                            </div>
                                            <div class="col-md-6 mb-2">
                                                <div>
                                                    @Html.Label("Bodega")
                                                    @*@Html.DropDownList("idBodega", lstBodegaProducto, null, new { @class = "form-control", id = "idBodega"})*@
                                                </div>
                                            </div>
                                            <div class="col-md-6 mb-2">
                                                @Html.Label("Existencias")
                                                @Html.TextBox("IdProducto", null, new { @class = "form-control", @ReadOnly = true })
                                            </div>
                                            <div class="col-md-6 mb-2">
                                                @Html.Label("Cantidad")
                                                @Html.TextBox("Cantidad", null, new { @class = "form-control" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <input action="action" onclick="window.history.go(-1); return false;" type="button" class="btn btn-success" value="Regresar" />
</div>



<script type="text/javascript">
    function cargarCombo(idProducto) {
        var idPro = idProducto;
            $.ajax({
                type: "GET",
                url: '@Url.Action("llenarBodegaXProductos", "Producto")',
                data: JSON.stringify({ id: idPro}),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
            });
    }

    $(function () {
        $('#idBodega').change(function () {
            var e = document.getElementById("idBodega");
            var f = document.getElementById("idProducto")
            var result = e.options[e.selectedIndex].value;
            var result2 = f.options[e.selectedIndex].value;
             $.ajax({
                    type: "GET",
                    traditional: true,
                    dataType: 'json',
                    data: { value: result, result2 },
                    url: '@Url.Action("CargarExistencia", "Producto")',
                    complete: function (data) {
                    }
                });
        });

     });
</script>

ServiWeb/ServiWeb/Views/Producto/Index.cshtml
@model List<ServiWeb.Models.ViewModels.ListaProductoViewModel>
@{
    ViewBag.Title = "Productos";
}

<h2>@ViewBag.Title</h2>

<div class="container-fluid" style="width:100%">

    <table table id="example" class="table table-striped table-bordered"
           style="width:100%">
        <thead>
            <tr>
                <th style="width: 5%">
                    Id
                </th>
                <th style="width: 20%">
                    Referencia
                </th>
                <th style="width: 40%">
                    Descripción
                </th>
                <th style="width: 15%">
                    Marca
                </th>
                <th style="width: 5%">
                    Unidad de Medida
                </th>
                <th style="width: 5%">
                    Dimensión
                </th>
                <th style="width: 5%">
                    IdCategoria
                </th>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Referencia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Marca)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnidadMedida)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Dimension)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdCategoria)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>