ServiWeb/ServiWeb/Controllers/OrdenVentaController.cs
using ServiWeb.Models;
using ServiWeb.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ServiWeb.Controllers
{
    public class OrdenVentaController : Controller
    {
        // GET: OrdenVenta
        public ActionResult Index()
        {
            llenarListaClientes();
            ViewBag.listaClientes = listaCliente;
            return View(listaCliente);
        }

        public void PasarIdCliente(string value)
        {
            var id = value;
            Session["idCliente"] = id;
        }

        public ActionResult NuevaOrden(OrdenViewModel modelo)
        {
            var id = Session["idCliente"];
            if (id != null)
            {
                int ClienteId = Convert.ToInt32(id);
                try
                {
                    var date = DateTime.Now;
                    using (DBORDENEntities1 db = new DBORDENEntities1())
                    {
                        modelo = (from d in db.Cliente.Where(d => d.idCliente == ClienteId)
                                  select new OrdenViewModel
                                  {
                                      IdCliente = d.idCliente,
                                      Nitcc = d.nitcc,
                                      Nombre = d.nombre,
                                      Fecha = date
                                  }).FirstOrDefault();
                    }
                    return View(modelo);
                } catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
            } else {
                TempData["testmsg"] = "Debe seleccionar un cliente antes de continuar";                
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult NuevaOrden(OrdenViewModel modelo, string operation)
        {
            List<ListaProductoConfirmadoViewModel> lstConfirmados = new List<ListaProductoConfirmadoViewModel>();
            List<OrdenTemporalListModel> temporales = new List<OrdenTemporalListModel>();
            
            var oTempo = new ProductoConfirmado();
            var oOrden = new Orden();
           
            var oDetalleOrden = new DetalleOrden();
            if (operation == "Confirmar Orden")
            {
                using (DBORDENEntities1 db = new DBORDENEntities1())
                {
                    if (modelo.OrdenTemporalListModel != null && modelo.SubTotal > 0)
                    {
                        foreach (var i in modelo.OrdenTemporalListModel)
                        {
                            //guardar en tabla productoConfirmado
                            oTempo.idProducto = i.IdProducto;
                            oTempo.idBodegaProducto = i.IdBodegaProducto;
                            oTempo.precio = i.PrecioVenta;
                            oTempo.cantidad = i.Cantidad;
                            oTempo.descripcion = i.Descripcion;
                            oTempo.idCliente = modelo.IdCliente;
                            oTempo.dcto = i.Dcto;
                            oTempo.estado = false;
                        }
                        db.ProductoConfirmado.Add(oTempo);
                        db.SaveChanges();
                        oOrden.idCliente = modelo.IdCliente;
                        oOrden.fecha = DateTime.Now;
                        oOrden.subTotal = oTempo.cantidad * oTempo.precio;
                        oOrden.total = oTempo.cantidad * oTempo.precio;
                        oOrden.estado = "Creada";
                        oOrden.numOrden = db.Consecutivo.Select(x => x.numOrden).FirstOrDefault();
                        oOrden.cerrada = true;
                        db.Orden.Add(oOrden);
                        db.SaveChanges();
                        int consecutivo = oOrden.numOrden;
                        int idOrden = oOrden.idOrden;

                        //// listar productos confirmados
                        lstConfirmados = (from pc in db.ProductoConfirmado
                                          where pc.idCliente == modelo.IdCliente && pc.estado == false
                                          select new ListaProductoConfirmadoViewModel
                                          {
                                              IdProducto = pc.idProducto,
                                              IdBodegaProducto = pc.idBodegaProducto,
                                              Precio = pc.precio,
                                              Cantidad = pc.cantidad,
                                              Descripcion = pc.descripcion,
                                              IdCliente = pc.idCliente,
                                              Dcto = pc.dcto,
                                              TotalProducto = pc.precio * pc.cantidad,
                                              Estado = pc.estado
                                          }).ToList();
                        modelo.ListaProductoConfirmadoViewModel = lstConfirmados;

                        //Guardar Detalle Orden
                        foreach (var v in lstConfirmados)
                        {
                            oDetalleOrden.idProducto = v.IdProducto;
                            oDetalleOrden.idBodegaProducto = v.IdBodegaProducto;
                            oDetalleOrden.cantidad = v.Cantidad;
                            oDetalleOrden.descuento = v.Dcto;
                            oDetalleOrden.total = v.Cantidad * v.Precio;
                            oDetalleOrden.numOrden = consecutivo;
                            oDetalleOrden.idOrden = idOrden;
                            db.DetalleOrden.Add(oDetalleOrden);
                            db.SaveChanges();
                        }
                    } else {
                        TempData["testmsg"] = "Debe seleccionar un producto y cantidad";
                    }
                }
            } else {
                
                if (modelo.OrdenTemporalListModel != null)
                {
                    using (DBORDENEntities1 db = new DBORDENEntities1())
                    {
                        foreach (var i in modelo.OrdenTemporalListModel)
                        {
                            if (i.Cantidad > 0)
                            {
                                //guardar en tabla productoConfirmado
                                oTempo.idProducto = i.IdProducto;
                                oTempo.idBodegaProducto = i.IdBodegaProducto;
                                oTempo.precio = i.PrecioVenta;
                                oTempo.cantidad = i.Cantidad;
                                oTempo.descripcion = i.Descripcion;
                                oTempo.idCliente = modelo.IdCliente;
                                oTempo.dcto = i.Dcto;
                                oTempo.estado = false;
                                db.ProductoConfirmado.Add(oTempo);
                                db.SaveChanges();
                            }
                        }
                        lstConfirmados = (from pc in db.ProductoConfirmado
                                          where pc.idCliente == modelo.IdCliente && pc.estado == false
                                          select new ListaProductoConfirmadoViewModel
                                          {
                                              IdProducto = pc.idProducto,
                                              IdBodegaProducto = pc.idBodegaProducto,
                                              Precio = pc.precio,
                                              Cantidad = pc.cantidad,
                                              Descripcion = pc.descripcion,
                                              IdCliente = pc.idCliente,
                                              Dcto = pc.dcto,
                                              TotalProducto = pc.precio * pc.cantidad,
                                              Estado = pc.estado
                                          }).ToList();

                        modelo.ListaProductoConfirmadoViewModel = lstConfirmados;
                    }
                }
                modelo.OrdenTemporalListModel = null;
                modelo.OrdenTemporalListModel = BuscarProductos(modelo.Busqueda);
            }              
            return View(modelo);
        }

        List<SelectListItem> listaCliente;
        public void llenarListaClientes()
        {
            int agente = Convert.ToInt32(Session["IdAgente"]);

            using (var db = new DBORDENEntities1())
            {
                listaCliente = (from Cliente in db.Cliente
                                where Cliente.idAsesor == agente
                                select new SelectListItem
                                {
                                    Text = Cliente.nombre,
                                    Value = Cliente.idCliente.ToString()
                                }).ToList();
                listaCliente.Insert(0, new SelectListItem { Text = "--Seleccione--", Value = "" });
                ViewBag.listaCliente = listaCliente;
            }
        }
                       
        public List<OrdenTemporalListModel> BuscarProductos(string Busqueda)
        {
            List<ListaProductoViewModel> lstGetProducto = new List<ListaProductoViewModel>();
            List<OrdenTemporalListModel> lstProducto = new List<OrdenTemporalListModel>();
            string busqueda = Busqueda;
            using (var db = new DBORDENEntities1())
            {
                if (busqueda == null)
                {
                    lstGetProducto = (from d in db.Producto

ServiWeb/ServiWeb/Views/OrdenVenta/HistoricoCliente.cshtml
@{
    ViewBag.Title = "HistoricoCliente";
}

<h2>HistoricoCliente</h2>

ServiWeb/ServiWeb/Views/OrdenVenta/Index.cshtml
@using ServiWeb.Models.ViewModels
@{
    ViewBag.Title = "Asesor de Ventas";
    List<SelectListItem> listaCliente = (List<SelectListItem>)ViewBag.listaClientes;
}
<script src="~/Scripts/script-custom-editor.js"></script>
<script src="~/Scripts/summernote-ext-rtl.js"></script>
<script src="~/Scripts/summernote.js"></script>
<link href="~/Content/summernote.css" rel="stylesheet" />


<div class="container">
    @using (Html.BeginForm())
    {<div class="container border">
            <h2>@ViewBag.Title</h2>
            <style>
                div {
                    text-align: center;
                }
            </style>
            <Center class=form-row>
                <label align="center">Clientes</label>
            </Center>
            <Center class=form-row>
                @Html.DropDownList("idCliente", listaCliente, null, new { @class = "form-control", id = "clientesDrop", style = "width:250px" })
                <textarea class="form-control" type="text" style="display:none" name="observacionText" id="text1"></textarea>
            </Center>
            <br />
            <br />
            <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                    <button type="button" id="btnHitorial" class="btn bg-warning">Historial Cliente</button>
                </div>
                <div class="col-sm">
                    @Html.ActionLink("Crear Orden", "NuevaOrden", "OrdenVenta", null, new { @class = "btn btn-default bg-warning" })
                </div>
                <div class="col-sm">
                </div>
            </div>
        </div>
    }
</div>


<script>
    $(function () {
        $('#clientesDrop').change(function () {
            var e = document.getElementById("clientesDrop");
            var result = e.options[e.selectedIndex].value;
            document.getElementById("text1").innerHTML = result;
             $.ajax({
                    type: "POST",
                    traditional: true,
                    dataType: 'json',
                    data: { value: result },
                    url: '@Url.Action("PasarIdCliente", "OrdenVenta")',
                    complete: function (data) {
                    }
                });
        });

     });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/bootstrap-select")
    @Styles.Render("~/Content/Bootstrap-Select/css")
    <script>
        $(function () {
            $("#clientesDrop").chosen();
        });
    </script>

}

@if (TempData["testmsg"] != null)
{
    <script type="text/javascript">
            alert("@TempData["testmsg"]");
    </script>
}

ServiWeb/ServiWeb/Views/OrdenVenta/NuevaOrden.cshtml
@model ServiWeb.Models.ViewModels.OrdenViewModel
@{
    ViewBag.Title = "Nueva Orden";

}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<div class="container-fluid" style="width:100%">
    @using (Html.BeginForm("NuevaOrden", "OrdenVenta", FormMethod.Post))
    {
        <div class="container border">
            <h2>@ViewBag.Title</h2>
            @Html.HiddenFor(model => Model.IdCliente)
            <div class="row">
                <div class="col"></div>
                <div class="col"></div>
                <div class="col"></div>
                <div class="col">
                    <label></label>
                    <input type="submit" name="operation" id="btnConfirmar" value="Confirmar Orden" class="btn btn-success" style="width:150px" />
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <label>Nit</label>
                    @Html.TextBoxFor(model => model.Nitcc, null, new { @class = "form-control", style = "width:150px", @readonly = "readonly" })
                </div>
                <div class="col">
                    <label>Nombre</label>
                    @Html.TextBoxFor(model => model.Nombre, null, new { @class = "form-control", style = "width:300px", @readonly = "readonly" })
                </div>
                <div class="col"></div>
                <div class="col">
                    <label>Fecha Creación</label>
                    @Html.TextBoxFor(model => model.Fecha, null, new { @class = "form-control", style = "width:150px", @readonly = "readonly" })
                </div>
            </div>
            <br />
            <div class="container border">
                <div class="row">
                    <div class="col-sm">
                        <label>SubTotal</label>
                        @Html.TextBox("subTotal", null, new { @class = "form-control", id = "subtotal", @ReadOnly = true })
                    </div>
                    <div class="col-sm">
                        <label>Total Dcto</label>
                        @Html.TextBox("totalDcto", null, new { @class = "form-control", id = "dcto", @ReadOnly = true })
                    </div>
                    <div class="col-sm">
                        <label>Vr. Iva</label>
                        @Html.TextBox("VrIva", null, new { @class = "form-control", id = "vriva", @ReadOnly = true })
                    </div>
                    <div class="col-sm">
                        <label>Total</label>
                        @Html.TextBox("total", null, new { @class = "form-control", id = "total", @ReadOnly = true })
                    </div>
                </div>
                <br />
            </div>
        </div>

        <br />

        <div class="container border" id="productos">
            <h4>Productos</h4>
            @Html.Label("Por favor ingrese un valor")
            @Html.TextBoxFor(model => model.Busqueda, new { htmlAttributes = new { @class = "form-control", @style = "text-transform:uppercase", @width = 50, id = "txtBuscar" } })
            <input type="submit" name="operation" id="btnBuscar" value="Buscar" class="btn btn-success" style="width:150px" onclick="borrar" />
            <br />
            <br />
            <div class="container-fluid" style="width:100%">
                <table table id="tblProductos" class="table table-striped table-bordered"
                       style="width:100%">
                    <thead>
                        <tr>
                            <th style="width: 5%">
                                Referencia
                            </th>
                            <th style="width: 40%">
                                Descripción
                            </th>
                            <th style="width: 15%">
                                Nombre Bodega
                            </th>
                            <th style="width: 10%">
                                Precio
                            </th>
                            <th style="width: 10%">
                                Existencia
                            </th>
                            <th style="width: 5%">
                                Cantidad
                            </th>
                            <th style="width: 15%">
                                Eliminar
                            </th>
                    </thead>
                    <tbody>
                        @Html.Hidden("myVarAnexos", 0)
                        @Html.EditorFor(model => model.OrdenTemporalListModel)
                    </tbody>
                </table>
            </div>
        </div>
        <br />

        <div class="container border" id="confirmados">
            <h4>Detalle Orden</h4>
            <table table id="example" class="table table-striped table-bordered"
                   style="width:100%">
                <thead>
                    <tr>
                        <th style="width: 50%">
                            Descripción
                        </th>
                        <th style="width: 10%">
                            Cantidad
                        </th>
                        <th style="width: 10%">
                            Precio Unitario
                        </th>
                        <th style="width: 10%">
                            Total
                        </th>
                        <th style="width: 10%">
                            Acción
                        </th>
                </thead>
                <tbody>
                    @Html.Hidden("myVarAnexos", 0)
                    @Html.EditorFor(model => model.ListaProductoConfirmadoViewModel)
                </tbody>
            </table>
        </div>
    }

    <br />
</div>

<script type="text/javascript">
    function borrar() {
        document.getElementById("txtBuscar").value = "";
    };
</script>


@if (TempData["testmsg"] != null)
{
    <script type="text/javascript">
            alert("@TempData["testmsg"]");
    </script>
}